<?php
$title=["澳洲经典虾", "鲜嫩碳烤鸡丁", "鲜嫩黑椒培根", "清新碳烤鸡丁", "鲜嫩经典虾", "美式芝士鸡丁", "澳洲芝士牛排", "清新经典培根", "美式碳烤虾", "澳洲经典培根", "美式芝士鸡丁", "美式碳烤培根", "鲜嫩经典虾", "清新香辣烤肉", "美式香辣虾", "澳洲香辣牛排", "法式芝士培根", "美式黑椒培根", "鲜嫩碳烤烤肉", "美式经典烤肉", "清新碳烤鸡丁", "美式香辣牛排", "法式经典牛排", "鲜嫩经典烤肉", "澳洲芝士鸡丁", "法式碳烤鸡丁", "法式香辣鸡丁", "鲜嫩碳烤鸡丁", "鲜嫩经典虾", "清新碳烤虾", "鲜嫩香辣牛排", "清新香辣烤肉", "鲜嫩黑椒虾", "清新黑椒培根", "清新经典培根", "美式碳烤虾", "清新经典鸡丁", "鲜嫩香辣烤肉", "清新黑椒牛排", "澳洲经典培根", "鲜嫩黑椒培根", "美式黑椒牛排", "美式芝士鸡丁", "美式黑椒牛排", "鲜嫩经典鸡丁", "清新黑椒烤肉", "澳洲香辣烤肉", "鲜嫩香辣鸡丁", "法式香辣鸡丁", "鲜嫩芝士鸡丁"];

$type=["type0", "type1", "type2", "type3", "type4", "type5", "type6", "type7", "type8", "type9", "type10", "type11", "type12", "type13", "type14", "type15", "type16", "type17", "type18", "type19", "type20", "type21", "type22", "type23", "type24", "type25", "type26", "type27", "type28", "type29", "type30", "type31", "type32", "type33", "type34", "type35", "type36", "type37", "type38", "type39", "type40", "type41", "type42", "type43", "type44", "type45", "type46", "type47", "type48", "type49"];

$detail=["Australia roast shrimp", "Australia cheese steak", "Australia roast steak", "American classic chicken", "Germany black peppersalmon", "Australia black peppershrimp", "Australia roast shrimp", "American roast salmon", "Freach cheese chicken", "Australia classic shrimp", "American classic salmon", "Freach classic shrimp", "Freach classic salmon", "Australia black peppersteak", "American roast shrimp", "Germany roast chicken", "Australia black pepperchicken", "Australia roast salmon", "Freach cheese chicken", "American classic salmon", "Australia cheese salmon", "Australia classic steak", "Australia classic salmon", "American classic salmon", "American roast salmon", "American classic shrimp", "Freach classic chicken", "Germany cheese shrimp", "Australia cheese chicken", "Germany cheese salmon", "Australia black peppershrimp", "American black peppershrimp", "American classic salmon", "Germany roast steak", "Germany roast steak", "American black peppershrimp", "Freach classic salmon", "Australia classic salmon", "American classic salmon", "Germany cheese shrimp", "American cheese salmon", "American cheese shrimp", "Freach cheese shrimp", "Freach cheese steak", "Germany roast salmon", "Germany classic salmon", "American roast chicken", "American classic chicken", "Australia roast steak", "Freach cheese shrimp"];

$img=["img/dishes/0.jpg", "img/dishes/1.jpg", "img/dishes/2.jpg", "img/dishes/3.jpg", "img/dishes/4.jpg", "img/dishes/5.jpg", "img/dishes/6.jpg", "img/dishes/7.jpg", "img/dishes/8.jpg", "img/dishes/9.jpg", "img/dishes/10.jpg", "img/dishes/11.jpg", "img/dishes/12.jpg", "img/dishes/13.jpg", "img/dishes/14.jpg", "img/dishes/15.jpg", "img/dishes/16.jpg", "img/dishes/17.jpg", "img/dishes/18.jpg", "img/dishes/19.jpg", "img/dishes/20.jpg", "img/dishes/21.jpg", "img/dishes/22.jpg", "img/dishes/23.jpg", "img/dishes/24.jpg", "img/dishes/25.jpg", "img/dishes/26.jpg", "img/dishes/27.jpg", "img/dishes/28.jpg", "img/dishes/29.jpg", "img/dishes/30.jpg", "img/dishes/31.jpg", "img/dishes/32.jpg", "img/dishes/33.jpg", "img/dishes/34.jpg", "img/dishes/35.jpg", "img/dishes/36.jpg", "img/dishes/37.jpg", "img/dishes/38.jpg", "img/dishes/39.jpg", "img/dishes/40.jpg", "img/dishes/41.jpg", "img/dishes/42.jpg", "img/dishes/43.jpg", "img/dishes/44.jpg", "img/dishes/45.jpg", "img/dishes/46.jpg", "img/dishes/47.jpg", "img/dishes/48.jpg", "img/dishes/49.jpg"];

require("../data/init.php");
for($i=0;$i<50;$i++){
	$sql="insert into food values(null,'$title[$i]','$type[$i]','$detail[$i]','$img[$i]')";
	mysqli_query($conn,$sql);
}
